name: Deploy Hosting

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:cuba-stage-hot-update
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
